# Generated by Django 4.0.6 on 2022-07-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='feature',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='estate_photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='kind',
            field=models.CharField(choices=[('HF', 'Пол с подогревом'), ('PO', 'Двор'), ('GN', 'Сад'), ('SP', 'Бассейн')], max_length=3, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='estate',
            name='tags',
            field=models.ManyToManyField(related_name='estate', to='estates.tag', verbose_name='теги'),
        ),
    ]
