# Generated by Django 4.0.4 on 2022-06-24 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='estate_videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='features',
            name='garages',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гаражи'),
        ),
    ]
