# Generated by Django 4.0.4 on 2022-07-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='estate_photos', verbose_name='Изображение'),
        ),
    ]
