# Generated by Django 4.0.4 on 2022-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_estate_video_alter_features_garages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='floors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество этажей'),
        ),
    ]
