# Generated by Django 4.0.4 on 2022-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_alter_estate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='kind',
            field=models.CharField(choices=[('HF', 'Пол с подогревом'), ('PO', 'Двор'), ('GN', 'Сад'), ('SP', 'Бассейн')], default=('N', 'None'), max_length=3, null=True, verbose_name='Тип'),
        ),
    ]
