# Generated by Django 4.0.6 on 2022-07-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_tag_alter_feature_unique_together_alter_estate_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
