# Generated by Django 4.0.4 on 2022-06-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_alter_features_floors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('bathrooms', models.IntegerField(verbose_name='Ванные комнаты')),
                ('bedrooms', models.IntegerField(verbose_name='Спальни')),
                ('garages', models.IntegerField(blank=True, null=True, verbose_name='Гаражи')),
                ('floors', models.IntegerField(blank=True, null=True, verbose_name='Количество этажей')),
                ('floor_on', models.IntegerField(verbose_name='Этаж')),
                ('estate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estates.estate')),
            ],
            options={
                'verbose_name': 'Особенности',
                'verbose_name_plural': 'Особенности',
            },
        ),
        migrations.AlterModelOptions(
            name='features',
            options={},
        ),
        migrations.RemoveField(
            model_name='features',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='features',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='features',
            name='estate',
        ),
        migrations.RemoveField(
            model_name='features',
            name='floor_on',
        ),
        migrations.RemoveField(
            model_name='features',
            name='floors',
        ),
        migrations.RemoveField(
            model_name='features',
            name='garages',
        ),
        migrations.AddField(
            model_name='features',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='features',
            name='details',
            field=models.ManyToManyField(to='estates.details'),
        ),
    ]
