# Generated by Django 4.0.4 on 2022-07-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0004_alter_feature_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='kind',
            field=models.CharField(choices=[('HF', 'Пол с подогревом'), ('PO', 'Двор'), ('GN', 'Сад'), ('SP', 'Бассейн')], default=0, max_length=3, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
