# Generated by Django 4.0.4 on 2022-06-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_alter_details_options_alter_features_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='floors',
            field=models.IntegerField(blank=True, default='---', null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='details',
            name='garages',
            field=models.IntegerField(blank=True, default='---', null=True, verbose_name='Гаражи'),
        ),
    ]
