# Generated by Django 4.0.6 on 2022-07-26 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0005_alter_tag_options_estate_latitude_estate_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estate',
            options={'ordering': ['-id'], 'verbose_name': 'Имущество', 'verbose_name_plural': 'Имущества'},
        ),
    ]
