# Generated by Django 4.0.4 on 2022-07-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_alter_details_floors_alter_details_garages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.SlugField(blank=True, max_length=256),
        ),
    ]
