# Generated by Django 4.0.6 on 2022-07-29 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0006_alter_estate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='photo',
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='houses')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estates.estate')),
            ],
        ),
    ]
