# Generated by Django 4.0.4 on 2022-07-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0007_alter_estate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='details',
        ),
        migrations.AddField(
            model_name='features',
            name='details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='estates.details', verbose_name='Детали'),
            preserve_default=False,
        ),
    ]
