# Generated by Django 4.0.6 on 2022-08-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0007_remove_estate_photo_estateimage'),
        ('estates', '0007_remove_estate_photo_houseimage'),
    ]

    operations = [
    ]
