# Generated by Django 4.0.4 on 2022-07-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0008_alter_feature_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='estate',
            name='photo',
            field=models.ImageField(max_length=255, upload_to='estate_photos/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='estate',
            name='tags',
            field=models.ManyToManyField(related_name='estate', to='estates.tag', verbose_name='теги'),
        ),
    ]
