# Generated by Django 4.0.4 on 2022-07-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0008_remove_features_details_features_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='estates.estate', verbose_name='Детали'),
        ),
    ]
