# Generated by Django 4.0.4 on 2022-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0009_alter_features_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='bathrooms',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Ванные комнаты'),
        ),
        migrations.AlterField(
            model_name='details',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Спальни'),
        ),
        migrations.AlterField(
            model_name='details',
            name='floor_on',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='details',
            name='floors',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество этажей'),
        ),
        migrations.AlterField(
            model_name='details',
            name='garages',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Гаражи'),
        ),
    ]
