# Generated by Django 4.0.4 on 2022-07-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0010_alter_details_bathrooms_alter_details_bedrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='estate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='estates.estate', verbose_name='Имущество'),
        ),
    ]
