# Generated by Django 4.0.4 on 2022-07-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0011_details_id_alter_details_estate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='features',
            old_name='details',
            new_name='estate',
        ),
    ]
